sudo: false
os: linux
language: go
go:
  - 1.11
  - 1.12

env:
  REPO_ROOT=$GOPATH/src/github.com/aimof/jason
  GO111MODULES=on
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.composer/cache

script:
  - cd $REPO_ROOT
  - go test .